rabbitmq:
  image: "rabbitmq:3-management"
  hostname: "rabbitmq"
  environment:
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
  ports:
    - "15672:15672"
    - "5672:5672"